version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: 'npm run start'
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
